---
title: "Lab 6-1 Solution"
author: "Kun Zhang"
date: "13 December 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#
```{r initialization}
poverty.data <- read.csv(
  "Data/poverty/poverty data - ACS_16_5YR_S1702_with_ann.csv",
  skip = 1, header = T)
dim(poverty.data)

drugs.mort.data <- read.table(
  "Data/mortality/Drugs and alcohol Cause of Death, 1999-2016.txt",
  sep = '\t', header = T)
dim(drugs.mort.data)

names(poverty.data)[3]
names(drugs.mort.data)[2]


```


```{r merge data}
library(dplyr)
library(plyr)

patterns <- c(" County| Parish| city")

# merge columns
county.data <- merge(
  poverty.data %>%
    mutate(below.poverty.rate = All.families....Percent.below.poverty.level..Margin.of.Error..Families) %>%
    select(Id2, below.poverty.rate), 
  drugs.mort.data %>%
    rename(replace=c("County.Code" = "Id2")) %>%
    rename(replace=c("Crude.Rate" = "mortality.rate")) %>%
    mutate(county = gsub(patterns, "", County)) %>%
    select(Id2, county, mortality.rate),
  by="Id2")

head(county.data)

# change "unreliabe" to NA
county.data <- county.data %>%
  mutate(mortality.rate = ifelse(mortality.rate == "Unreliable", NA, mortality.rate) %>%
           as.numeric(as.character(mortality.rate)))


```

```{r Correlation plots}
library(ggplot2)
library(scales)

# plotting jitters (points + noises) 
ggplot(county.data, aes(y=mortality.rate, x=(below.poverty.rate / 100))) +
  geom_jitter(size = .5, alpha = .25, width = .01, height = .5) +
  stat_smooth(se=FALSE, fullrange=TRUE) + # Aids the eye in seeing patterns in the presence of overplotting
  labs(title = "County-level drug/alcohol related mortality rate\nversus poverty rate",
       y = "Drug/alcohol related mortality rate\n(per 100,000 population)\n",
       x = "Families below poverty level (%)") +
  scale_x_continuous(labels = percent) +
  theme_minimal() +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(colour="grey", size=0.4),
        panel.grid.minor = element_blank(),
        legend.position="none",
        plot.title = element_text(size=12, face="bold", vjust=2.7, hjust=.5),
        strip.text.x = element_text(size=13, vjust=1),
        strip.background = element_blank(),
        axis.title.x = element_text(size=13, vjust=-.75),
        axis.title.y = element_text(size=13, vjust=1.5),
        axis.text.x = element_text(size=9, vjust=-.25),
        axis.text.y = element_text(size=9, hjust=1))

# split the "Bullock, AL" by , and only choose AL
county.data$state <- sapply(strsplit(as.character(county.data$county) , "\\, ") , "[" , 2)


# reorder states by correlation order
state.order <- ddply(county.data, .(state), summarize,
                     correlation = cor(mortality.rate, below.poverty.rate, use='pairwise'))
county.data <- left_join(county.data, state.order)
county.data$state <- reorder(county.data$state, county.data$correlation)
county.data <- county.data[order(county.data$state),]


ggplot(county.data, aes(y=mortality.rate, x=(below.poverty.rate / 100))) +
  geom_jitter(size = .5, alpha = .25, width = .01, height = .5) +
  stat_smooth(se=FALSE, fullrange=TRUE) + # Aids the eye in seeing patterns in the presence of overplotting
  labs(title = "County-level drug/alcohol related mortality rate\nversus poverty rate",
       y = "Drug/alcohol related mortality rate\n(per 100,000 population)\n",
       x = "Families below poverty level (%)") +
  scale_x_continuous(labels = percent) +
  theme_minimal() +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.major.y = element_line(colour="grey", size=0.4),
        panel.grid.minor = element_blank(),
        legend.position="none",
        plot.title = element_text(size=12, face="bold", vjust=2.7, hjust=.5),
        strip.text.x = element_text(size=13, vjust=1),
        strip.background = element_blank(),
        axis.title.x = element_text(size=13, vjust=-.75),
        axis.title.y = element_text(size=13, vjust=1.5),
        axis.text.x = element_text(size=9, vjust=-.25),
        axis.text.y = element_text(size=9, hjust=1)) +
  facet_wrap(~state)

```

## regression
```{r Regression plots}
library(arm)
opioids.data <- read.csv("Data/opioids/opioids prescribing rates.csv")


county.data <- merge(
  county.data %>%
    mutate(z.poverty = scale(below.poverty.rate)),
  opioids.data %>%
    mutate(county = ï..County) %>%
    mutate(z.opiates = scale(X2016.Prescribing.Rate)) %>%
    select(county, z.opiates, X2016.Prescribing.Rate),
  by = "county")


# Linear model
mortality.model.1 <- glm(mortality.rate ~ z.poverty + z.opiates,
                         family=poisson(link = log),
                         data=county.data)
mortality.model.2 <- glmer(mortality.rate ~ z.poverty + z.opiates + (1 | state),
                           family=poisson(link = log),
                           data=county.data)

display(mortality.model.1)
display(mortality.model.2)

mortality.model.2.intercepts <- cbind(ranef(mortality.model.2)$state, se.ranef(mortality.model.2)$state)

```

# Interactive Map
```{r Interactive Map}
library(rgdal)
us.shape.1 <- readOGR(".","cb_2016_us_county_20m")
us.shape.2 <- spTransform(us.shape.1, CRS("+init=epsg:4326"))